{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-plugin-gradle",
    "version": "6.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "2.31.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib-extra",
          "version": {
            "requires": "2.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-plugin-gradle-6.12.0.jar",
          "url": "spotless-plugin-gradle-6.12.0.jar",
          "size": 116969,
          "sha512": "60b5ffc27798208beef6aac864642f8fe0f287b9394f0b5723b8775950ab60c7cb617c4267c8178f6777ccb4cc123c4ae50518be90453d21c751f6ed2aefcf2a",
          "sha256": "54293b86170b821115772090bb90aeb466cda6bf9e08b06bacbd3bb94a714e1f",
          "sha1": "4bace71cc3201f9de81752b32f94532004bdaa4b",
          "md5": "3d4589aa3a8bfe9589d7aba458259bcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.diffplug.durian",
          "module": "durian-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-io",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-collect",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.1.202206130422-r"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "2.31.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib-extra",
          "version": {
            "requires": "2.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-plugin-gradle-6.12.0.jar",
          "url": "spotless-plugin-gradle-6.12.0.jar",
          "size": 116969,
          "sha512": "60b5ffc27798208beef6aac864642f8fe0f287b9394f0b5723b8775950ab60c7cb617c4267c8178f6777ccb4cc123c4ae50518be90453d21c751f6ed2aefcf2a",
          "sha256": "54293b86170b821115772090bb90aeb466cda6bf9e08b06bacbd3bb94a714e1f",
          "sha1": "4bace71cc3201f9de81752b32f94532004bdaa4b",
          "md5": "3d4589aa3a8bfe9589d7aba458259bcc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-plugin-gradle-6.12.0-javadoc.jar",
          "url": "spotless-plugin-gradle-6.12.0-javadoc.jar",
          "size": 501259,
          "sha512": "4fef8f0cc494bd4efce5fbbfaf2315e4e3748493a653e5995feb9cace75399627f92c1ee7cb221d9f6ce7bb81cff99a4b2cb945b5654c20db35b8a84cf348006",
          "sha256": "311538d05dafc38c77fa6ccfe31caee39e2ce7522d69df1b53ed65b224718bfd",
          "sha1": "63678e747c48181851a7e2223daf728c0a47347e",
          "md5": "1e0f2f86f463314fe9415cbd3db8d027"
        },
        {
          "name": "spotless-plugin-gradle-6.12.0-javadoc.jar",
          "url": "spotless-plugin-gradle-6.12.0-javadoc.jar",
          "size": 501259,
          "sha512": "4fef8f0cc494bd4efce5fbbfaf2315e4e3748493a653e5995feb9cace75399627f92c1ee7cb221d9f6ce7bb81cff99a4b2cb945b5654c20db35b8a84cf348006",
          "sha256": "311538d05dafc38c77fa6ccfe31caee39e2ce7522d69df1b53ed65b224718bfd",
          "sha1": "63678e747c48181851a7e2223daf728c0a47347e",
          "md5": "1e0f2f86f463314fe9415cbd3db8d027"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-plugin-gradle-6.12.0-sources.jar",
          "url": "spotless-plugin-gradle-6.12.0-sources.jar",
          "size": 57962,
          "sha512": "88ad92d769a7641784948b17efec203b28e93ad492934a3c94c2a6cbb9ab35dd13e53631f180666231a2bbfabba9a58730dc6177c82492d65cdae3c98ed16fe0",
          "sha256": "75d5d9382db49d31fe117de53186fc7bc94b57585809bc6dbf080d566d959ef3",
          "sha1": "88d671409ab4c5630f13ca2e30bc15514e614d0b",
          "md5": "b5f3a7d60f86928c012e511995b0b1c7"
        },
        {
          "name": "spotless-plugin-gradle-6.12.0-sources.jar",
          "url": "spotless-plugin-gradle-6.12.0-sources.jar",
          "size": 57962,
          "sha512": "88ad92d769a7641784948b17efec203b28e93ad492934a3c94c2a6cbb9ab35dd13e53631f180666231a2bbfabba9a58730dc6177c82492d65cdae3c98ed16fe0",
          "sha256": "75d5d9382db49d31fe117de53186fc7bc94b57585809bc6dbf080d566d959ef3",
          "sha1": "88d671409ab4c5630f13ca2e30bc15514e614d0b",
          "md5": "b5f3a7d60f86928c012e511995b0b1c7"
        }
      ]
    }
  ]
}
